# This file is part of Toan Machine and is licensed under the GPLv3
# https://www.gnu.org/licenses/gpl-3.0.en.html
# SPDX-License-Identifier: GPL-3.0-only

from toan.model.nam_a1_wavenet_config import (
    NamA1WaveNetConfig,
    NameA1WaveNetLayerGroupConfig,
)
from toan.model.presets import ModelConfigPreset


def get_a1_wavenet_config(size_preset: ModelConfigPreset) -> NamA1WaveNetConfig | None:
    match size_preset:
        case ModelConfigPreset.NAM_A1_STANDARD:
            return NamA1WaveNetConfig(
                layers=[
                    NameA1WaveNetLayerGroupConfig(
                        input_size=1,
                        condition_size=1,
                        head_size=8,
                        channels=16,
                        kernel_size=3,
                        dilations=[
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                            128,
                            256,
                            512,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=False,
                    ),
                    NameA1WaveNetLayerGroupConfig(
                        input_size=16,
                        condition_size=1,
                        head_size=1,
                        channels=8,
                        kernel_size=3,
                        dilations=[
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                            128,
                            256,
                            512,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=True,
                    ),
                ]
            )
        case ModelConfigPreset.NAM_A1_LITE:
            return NamA1WaveNetConfig(
                layers=[
                    NameA1WaveNetLayerGroupConfig(
                        input_size=1,
                        condition_size=1,
                        head_size=6,
                        channels=12,
                        kernel_size=3,
                        dilations=[
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=False,
                    ),
                    NameA1WaveNetLayerGroupConfig(
                        input_size=12,
                        condition_size=1,
                        head_size=1,
                        channels=6,
                        kernel_size=3,
                        dilations=[
                            128,
                            256,
                            512,
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                            128,
                            256,
                            512,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=True,
                    ),
                ]
            )
        case ModelConfigPreset.NAM_A1_FEATHER:
            return NamA1WaveNetConfig(
                layers=[
                    NameA1WaveNetLayerGroupConfig(
                        input_size=1,
                        condition_size=1,
                        head_size=4,
                        channels=8,
                        kernel_size=3,
                        dilations=[
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=False,
                    ),
                    NameA1WaveNetLayerGroupConfig(
                        input_size=8,
                        condition_size=1,
                        head_size=1,
                        channels=4,
                        kernel_size=3,
                        dilations=[
                            128,
                            256,
                            512,
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                            128,
                            256,
                            512,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=True,
                    ),
                ]
            )
        case ModelConfigPreset.TOAN_A1_STANDARD_PLUS:
            return NamA1WaveNetConfig(
                layers=[
                    NameA1WaveNetLayerGroupConfig(
                        input_size=1,
                        condition_size=1,
                        head_size=12,
                        channels=24,
                        kernel_size=3,
                        dilations=[
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                            128,
                            256,
                            512,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=False,
                    ),
                    NameA1WaveNetLayerGroupConfig(
                        input_size=24,
                        condition_size=1,
                        head_size=1,
                        channels=12,
                        kernel_size=3,
                        dilations=[
                            1,
                            2,
                            4,
                            8,
                            16,
                            32,
                            64,
                            128,
                            256,
                            512,
                        ],
                        activation="Tanh",
                        gated=False,
                        head_bias=True,
                    ),
                ]
            )
        case _:
            return None
