name: Build macOS DMG

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install virtualenv
        run: python -m pip install virtualenv

      - name: Create virtual environment
        run: python -m virtualenv .venv

      - name: Build DMG
        run: ./script/build_macos.sh
